version: '3'

services:
  surge_scraper:
    build: .
    depends_on:
      - influxdb
      - grafana
    container_name: Surge_scraper

  influxdb:
    image: influxdb:2.7.4-alpine
    container_name: Influxdb_v2
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-init-user # Change to your preferred value. 
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-init-password # Change to your preferred value. 8 digs at least. 
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-init-token # could be the same as password. 
      - DOCKER_INFLUXDB_INIT_ORG=my-init-org # Change to your preferred value. 
      - DOCKER_INFLUXDB_INIT_BUCKET=my-init-bucket # Change to your preferred value. 
      - DOCKER_INFLUXDB_INIT_RETENTION=1y # 1y is the data that will be retent one year. 
    ports:
      - "8086:8086"
    restart: unless-stopped

  grafana-oss:
    image: grafana/grafana-oss:latest
    container_name: Grafana-oss
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Change to your preferred value
      - GF_SECURITY_ADMIN_PASSWORD=admin # Change to your preferred value
    ports:
      - "3000:3000"
    restart: unless-stopped


volumes:
  influxdb_data:
    driver: local
    driver_opts:
      type: none
      device: /path/to/your/influxdb_data
      o: bind
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: /path/to/your/grafana_data
      o: bind

